// ── TWO WAYS TO PRICE THE SAME LABOR, AND THE APP ADDS THEM ──────────────────
// A working estimator, on the labor-unit questions: "all those questions is if
// they bid the job using time and materials."
//
// He is describing two different methods, and the app supports both:
//
//   PERIODS — how a lump-sum remodel is actually bid. "Medium Temp Cases, four
//   men, six nights." You price the crew and the calendar off the schedule and
//   the unit hours never enter it.
//
//   UNIT BUILD-UP — the T&M / unit-price method. Hours per foot, per joint, per
//   case, multiplied through the circuit list. This is what the circuit labor
//   estimator does, and what every labor-unit question was about.
//
// They are two prices for the SAME work — running and connecting the circuits.
// bidTotals sums laborTotal + rackLaborTotal + fieldTasksTotal, so a job that
// has periods filled in AND field tasks generated from its circuits carries the
// running labor twice. On eleven circuits at ~17 man-hours each that is around
// nineteen thousand dollars of duplicate labor, and nothing said a word.
//
// The app must not silently pick one — that would change bids under people. It
// says plainly that both are present and what each comes to.

export function laborDoubleCount({
  periodsTotal = 0, fieldTasksTotal = 0, rackLaborTotal = 0, autoGeneratedCount = 0,
} = {}) {
  const bulk = Number(periodsTotal) || 0;
  const tasks = (Number(fieldTasksTotal) || 0) + (Number(rackLaborTotal) || 0);
  if (bulk <= 0 || tasks <= 0) return null;

  // Tasks the circuit estimator produced are unambiguously the same work the
  // period crews are there to do. Hand-entered tasks might be genuine extras —
  // a separate mobilisation, a punch item — so those are raised more gently.
  const generated = Number(autoGeneratedCount) || 0;
  return {
    severity: generated > 0 ? 'blocker' : 'verify',
    periodsTotal: bulk,
    tasksTotal: tasks,
    autoGeneratedCount: generated,
    combined: bulk + tasks,
    message: generated > 0
      ? `This bid carries labor twice. The crew periods come to ${money(bulk)} and the task list adds `
        + `another ${money(tasks)}, and ${generated} of those task${generated === 1 ? ' was' : 's were'} generated `
        + 'from the circuits — the same running and connecting the period crews are there to do. '
        + 'Crew-and-nights is how a lump-sum job is priced; the per-circuit hours are the time-and-materials '
        + 'way of reaching the same number. Use one. Clear the generated tasks, or set the period days to zero.'
      : `Both labor methods are filled in: crew periods at ${money(bulk)} and a task list at ${money(tasks)}, `
        + `and the bid carries ${money(bulk + tasks)}. That is right only if the tasks are work the period crews `
        + 'are not already covering. If they are the same work, this bid is double.',
  };
}

// The estimator's own hours are stored on the tasks, so "was this generated"
// has to be read off the note the generator leaves. Cheap, and it survives the
// user editing the hours afterwards — which they should.
export function countGeneratedTasks(tasks = []) {
  return (tasks || []).filter(t => /auto-estimated/i.test(String(t?.notes || ''))).length;
}

// ── WHY A REMODEL IS THE WRONG JOB TO CALIBRATE ON ───────────────────────────
// Same estimator: "on remodels those numbers will always be different. New jobs
// would be a more accurate assessment."
//
// He is right, and it is the reason the unit library should not be trusted
// equally everywhere. A ground-up store is a clean run through an empty
// building. A remodel is working around pipe that is already there, cases that
// are still running, and a store full of customers until close.
export function unitReliability(projectType) {
  return (projectType || 'remodel') === 'new'
    ? {
      level: 'better',
      note: 'New construction — a clean run through an empty building is what these units describe best, '
        + 'and it is the job worth checking them against.',
    }
    : {
      level: 'varies',
      note: 'Remodel — unit hours vary most here. Working around existing pipe, cases that are still running '
        + 'and a store that is open until close is not the same work as a clean run, and no per-foot rate '
        + 'captures the difference. Treat the estimate as a starting point and lean on the crew-and-nights '
        + 'figure you would actually bid.',
    };
}

function money(n) {
  return '$' + Math.round(n).toLocaleString('en-US');
}
