import { describe, it, expect } from 'vitest';
import { laborDoubleCount, countGeneratedTasks, unitReliability } from './laborMethod.js';

// ── THE TWO METHODS ──────────────────────────────────────────────────────────
// Crew-and-nights is how a lump-sum remodel gets bid. Hours-per-foot is the
// time-and-materials way of reaching the same number. bidTotals adds
// laborTotal + rackLaborTotal + fieldTasksTotal, so a job carrying both prices
// the running labor twice.

describe('catching a job priced by both methods', () => {
  it('says nothing when only the crew periods are filled in', () => {
    // The normal lump-sum job. Nothing wrong with it.
    expect(laborDoubleCount({ periodsTotal: 84000, fieldTasksTotal: 0 })).toBe(null);
  });

  it('says nothing when only the task list is filled in', () => {
    // The normal unit-priced job. Also fine.
    expect(laborDoubleCount({ periodsTotal: 0, fieldTasksTotal: 19000 })).toBe(null);
  });

  it('fires when both carry money', () => {
    const d = laborDoubleCount({ periodsTotal: 84000, fieldTasksTotal: 19000 });
    expect(d).toBeTruthy();
    expect(d.combined).toBe(103000);
  });

  it('treats generated circuit tasks as the serious case', () => {
    // A task the circuit estimator produced is unambiguously the work the
    // period crews are there to do. There is no reading where both belong.
    const d = laborDoubleCount({ periodsTotal: 84000, fieldTasksTotal: 19000, autoGeneratedCount: 11 });
    expect(d.severity).toBe('blocker');
    expect(d.message).toMatch(/carries labor twice/i);
    expect(d.message).toMatch(/11 of those tasks were generated/i);
  });

  it('is gentler about hand-entered tasks', () => {
    // Those might be a real extra — a separate mobilisation, a punch item.
    const d = laborDoubleCount({ periodsTotal: 84000, fieldTasksTotal: 4000 });
    expect(d.severity).toBe('verify');
    expect(d.message).toMatch(/right only if/i);
  });

  it('counts rack labor on the task side, where it is billed', () => {
    // bidTotals adds rackLaborTotal alongside fieldTasksTotal. A job with
    // periods and rack tasks and no field tasks is the same trap.
    const d = laborDoubleCount({ periodsTotal: 50000, fieldTasksTotal: 0, rackLaborTotal: 8000 });
    expect(d).toBeTruthy();
    expect(d.tasksTotal).toBe(8000);
  });

  it('names both numbers so the estimator can see which to drop', () => {
    const d = laborDoubleCount({ periodsTotal: 84000, fieldTasksTotal: 19000, autoGeneratedCount: 11 });
    expect(d.message).toContain('$84,000');
    expect(d.message).toContain('$19,000');
  });

  it('survives junk and an empty call', () => {
    expect(laborDoubleCount()).toBe(null);
    expect(laborDoubleCount({})).toBe(null);
    expect(laborDoubleCount({ periodsTotal: NaN, fieldTasksTotal: 'x' })).toBe(null);
    expect(laborDoubleCount({ periodsTotal: -5, fieldTasksTotal: 100 })).toBe(null);
  });
});

describe('spotting the tasks the estimator generated', () => {
  it('finds them by the note the generator leaves', () => {
    const tasks = [
      { desc: 'Run & connect C1', notes: 'Auto-estimated — 17.3 man-hours over 2 men' },
      { desc: 'Run & connect C2', notes: 'Auto-estimated — 9.1 man-hours over 2 men' },
      { desc: 'Haul off old cases', notes: 'From scope doc' },
      { desc: 'Punch list', notes: '' },
    ];
    expect(countGeneratedTasks(tasks)).toBe(2);
  });

  it('still recognises one after the hours have been edited', () => {
    // The estimator is meant to correct these. Losing track of where a task
    // came from the moment somebody fixes it would defeat the check.
    expect(countGeneratedTasks([{ hrs: 40, notes: 'Auto-estimated — 17.3 man-hours over 2 men' }])).toBe(1);
  });

  it('survives tasks with no notes at all', () => {
    expect(countGeneratedTasks([{}, null, undefined])).toBe(0);
    expect(countGeneratedTasks()).toBe(0);
  });
});

describe('which jobs these units actually describe', () => {
  it('calls new construction the job worth calibrating on', () => {
    const r = unitReliability('new');
    expect(r.level).toBe('better');
    expect(r.note).toMatch(/empty building/i);
  });

  it('warns that a remodel is where the units vary most', () => {
    // Existing pipe, cases still running, a store open until close. No
    // per-foot rate captures that, and pretending otherwise is how an
    // estimate looks confident and lands short.
    const r = unitReliability('remodel');
    expect(r.level).toBe('varies');
    expect(r.note).toMatch(/existing pipe/i);
  });

  it('treats an unset project type as a remodel', () => {
    // Which is the app's own default, and the more cautious of the two.
    for (const v of [undefined, null, '']) {
      expect(unitReliability(v).level, String(v)).toBe('varies');
    }
  });
});
