// ── HVAC PARTS TABLE GROUPING ───────────────────────────────────────────────────
// A big mechanical set lands ~100 takeoff lines in the parts table — duct sizes,
// pipe, VAV boxes, purchase-unit rollups — in extraction order, one flat pile.
// This module partitions them into collapsible sections and sorts inside each,
// so the table reads like an estimate summary instead of a scroll marathon.
// Pure functions over the parts array; the React side only renders the result.
import { parseDuctDesc, ductServiceOf } from './ductwork.js';
import { isTerminalUnit } from './hvacEquip.js';

// Section order is fixed — takeoff evidence (duct footage) first, then the
// purchase rollup that actually prices, then countable boxes, pipe, misc.
export const PART_GROUPS = [
  { key: 'duct-rect', label: 'Ductwork — rectangular', icon: '🌀', qtyUnit: 'ft' },
  { key: 'duct-round', label: 'Ductwork — round & flex', icon: '⭕', qtyUnit: 'ft' },
  { key: 'purchase', label: 'Duct purchase units', icon: '🧾', qtyUnit: '' },
  { key: 'terminal', label: 'VAV / terminal boxes', icon: '📦', qtyUnit: 'ea' },
  { key: 'pipe', label: 'Pipe', icon: '〰️', qtyUnit: 'ft' },
  { key: 'other', label: 'Other parts & materials', icon: '🔧', qtyUnit: '' },
];

export function partGroupOf(p = {}) {
  if (p.dgen) return 'purchase'; // generated by the Duct→Purchase calculator
  const desc = String(p.desc || '');
  const duct = parseDuctDesc(desc);
  if (duct) return duct.kind === 'rect' ? 'duct-rect' : 'duct-round';
  if (/^\s*pipe\b|—\s*pipe\b/i.test(desc)) return 'pipe';
  if (isTerminalUnit({ type: desc })) return 'terminal';
  return 'other';
}

// Sort duct lines the way an estimator scans a plan: by service (supply →
// return → exhaust → OA), then biggest size first, then name. Everything
// else alphabetical.
const SERVICE_RANK = { supply: 0, return: 1, exhaust: 2, oa: 3, '': 4 };
function ductSortKey(p) {
  const d = parseDuctDesc(p.desc) || {};
  const size = d.kind === 'rect' ? (d.w || 0) * (d.h || 0) : (d.dia || 0) * (d.dia || 0);
  return [SERVICE_RANK[ductServiceOf(p.desc)] ?? 4, -size];
}
export function sortGroupParts(key, parts) {
  const arr = [...parts];
  if (key === 'duct-rect' || key === 'duct-round') {
    arr.sort((a, b) => {
      const ka = ductSortKey(a), kb = ductSortKey(b);
      return (ka[0] - kb[0]) || (ka[1] - kb[1]) || String(a.desc).localeCompare(String(b.desc));
    });
  } else {
    arr.sort((a, b) => String(a.desc).localeCompare(String(b.desc)));
  }
  return arr;
}

// → ordered [{ key, label, icon, qtyUnit, parts, count, qtySum, pricedCount,
//    subtotal }], only groups that have lines. Each group's header numbers let
// the collapsed table still read as a summary.
export function groupHvacParts(parts = []) {
  const buckets = new Map();
  for (const p of parts) {
    const key = partGroupOf(p);
    if (!buckets.has(key)) buckets.set(key, []);
    buckets.get(key).push(p);
  }
  return PART_GROUPS.filter(g => buckets.has(g.key)).map(g => {
    const items = sortGroupParts(g.key, buckets.get(g.key));
    return {
      ...g,
      parts: items,
      count: items.length,
      qtySum: items.reduce((s, p) => s + (Number(p.qty) || 0), 0),
      pricedCount: items.filter(p => (Number(p.unitCost) || 0) > 0).length,
      subtotal: items.reduce((s, p) => s + (Number(p.total) || 0), 0),
    };
  });
}
